const products = [
	{
		category: 'nike',
		img: 'https://i.ibb.co/s1kgsRZ/af1-gray.jpg',
		price: 15000,
		title: 'Air Force 1 Gray',
		id: 'xXaaB2sBl0l74aucAPQk',
		quantity: 1,
	},

	{
		category: 'wonder',
		img: 'https://i.ibb.co/qNpsGxG/wonder-black.jpg',
		price: 12000,
		title: 'Wonder Black',
		id: '89XO54yBIR38rhg1dZyM',
		quantity: 1,
	},
	{
		category: 'detroit',
		img: 'https://i.ibb.co/pWjj1gV/detroit-golden.jpg',
		price: 12000,
		title: 'Detroit Golden',
		id: 'vPDYn3vK07d0zWdBTHYz',
		quantity: 1,
	},
	{
		category: 'detroit',
		img: 'https://i.ibb.co/Hh5tDwp/detroit-white.jpg',
		price: 12000,
		title: 'Detroit White',
		id: 'Bbdg7UHuQuZwlApZkNq1',
		quantity: 1,
	},
	{
		category: 'detroit',
		img: 'https://i.ibb.co/2tpDjqB/detroti-black-black.jpg',
		price: 12000,
		title: 'Detroit Black',
		id: 'f8vblFiflPoEwypyLgpQ',
		quantity: 1,
	},
	{
		category: 'nike',
		img: 'https://i.ibb.co/G0xtVHd/af1-black.jpg',
		price: 15000,
		title: 'Air Force 1 Black',
		id: 'htOkLFUF8WjijI9Ty265',
		quantity: 1,
	},
	{
		category: 'wonder',
		img: 'https://i.ibb.co/4Vq8ycB/wonder-white.jpg',
		price: 12000,
		title: 'Wonder White',
		id: 'WfxRbmV1tG1uO5ejYmOH',
		quantity: 1,
	},
	{
		category: 'nike',
		img: 'https://i.ibb.co/xDkRG94/af1-white.jpg',
		price: 15000,
		title: 'Air Force 1 White',
		id: 'lXNWBSEPiKES7Zm5Mcs1',
		quantity: 1,
	},
];
export default products;
